# api gateway config
spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - name: LoggingOrderFilter
            - name: Authentication
              args:
                isEnabled: false
            - name:
                args:
                  allowedRoles:
                    - ADMIN
                    - SUPER_ADMIN
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - name: Authentication


#eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secretKey: lskdfjj0wee8ff0d9f09cvjj7w86g86gdigf79x7ycvohd9s8yhy7eg8ghfidhc98xyhhcvigi7
